In [1]:
from rampr.io import national
import inspect

f = national.read_use_make

print("module file:", national.__file__)
print("function module:", f.__module__)
print("filename:", f.__code__.co_filename)
print("first line:", f.__code__.co_firstlineno)
print("argcount:", f.__code__.co_argcount)
print("varnames:", f.__code__.co_varnames)

module file: /home/serge/projects/dev-rampr/rampr/io/national.py
function module: rampr.io.national
filename: /home/serge/projects/dev-rampr/rampr/io/national.py
first line: 153
argcount: 0
varnames: ('pth', 'use', 'U', 'make', 'V', 'g', 'q', 'qd', 'gd')


In [2]:
from rampr.io import national
import pandas as pd
import numpy as np

In [3]:
use, make, U, V, g, q= national.read_use_make()

In [4]:
print(national.__file__)

/home/serge/projects/dev-rampr/rampr/io/national.py


In [5]:
import inspect

In [6]:
from rampr.io import national
import pandas as pd
import numpy as np

In [7]:
print(inspect.getsource(national.read_use_make))

def read_use_make():
    pth = "../data/raw/io"
    use = pd.read_excel(pth+"/IOUse_After_Redefinitions_PRO_Detail.xlsx",
                        sheet_name='2017',
                        skiprows=[0,1,2,3])
    use = use.iloc[1:].reset_index(drop=True)
    U = (
        use.iloc[:, 2:].apply(pd.to_numeric, errors="coerce").fillna(0.0)
    )
    
    
    make = pd.read_excel(pth+"/IOMake_After_Redefinitions_PRO_Detail.xlsx",
                        sheet_name='2017',
                        skiprows=[0,1,2,3])
    make = make.iloc[1:].reset_index(drop=True)
    V = (
        make.iloc[:, 2:].apply(pd.to_numeric, errors="coerce").fillna(0.0)
    )
    g = U.values[-1,:402]
    q = U.values[:402, -1]
    
    qd = q + (q==0)
    gd = g + (g==0)

    #D = V @ np.diag(1/qd)
    #B = U @ np.diag(1/gd)

    #A = D @ B
    #L = np.linalg.inv(np.eye(402) - A)
    
    return use, make, U, V, g, q



In [8]:
U.shape

(408, 425)

In [9]:
gd = g + 1 * (g==0)

In [10]:
B = U.values[:402, :402] @ np.diag(1/gd)

In [11]:
qd = q + 1 * (q==0)

In [12]:
D = V.values[:402, :402] @ np.diag(1/qd)

In [13]:
A = D @ B

In [14]:
L = np.linalg.inv(np.eye(402) - A)

In [15]:
L.sum(axis=0)

array([2.05558814, 2.69238156, 2.08768823, 1.71722196, 1.92477905,
       2.29876104, 2.69137064, 2.70900612, 3.23801568, 1.62662021,
       1.74046682, 1.44317351, 1.37947947, 1.69210376, 2.25826851,
       2.02090742, 2.29235427, 1.99584314, 2.02231908, 1.87636015,
       1.875264  , 1.57954877, 1.60688814, 1.53770044, 1.70609756,
       1.84987646, 1.98994556, 1.86481188, 2.00713142, 1.83346224,
       2.1148608 , 1.81661707, 1.81841361, 1.51588406, 1.85690718,
       1.9367907 , 2.44591666, 2.4053604 , 2.42393405, 2.49158407,
       1.98037158, 2.11508889, 1.8610292 , 2.25144191, 2.00459513,
       2.07264336, 2.05691461, 1.7110426 , 2.0985669 , 2.10267261,
       2.00579862, 2.05617499, 2.62549898, 2.65941401, 2.88133949,
       2.70372271, 2.91660799, 2.62615293, 3.14968841, 2.55850346,
       2.23023273, 2.30806038, 2.72024849, 2.48960131, 2.37288697,
       2.20493679, 2.56608584, 2.37455241, 2.34180563, 2.33048058,
       2.70303663, 2.44293299, 2.3652426 , 2.03886525, 2.32027

In [16]:
g

array([3.821600e+04, 5.788200e+04, 1.880600e+04, 2.995800e+04,
       2.006400e+04, 2.657500e+04, 3.853800e+04, 8.805200e+04,
       4.456800e+04, 3.344300e+04, 1.972900e+04, 8.929000e+03,
       2.540700e+04, 2.380920e+05, 2.782700e+04, 1.289000e+04,
       1.442400e+04, 1.447900e+04, 1.676400e+04, 2.815000e+04,
       9.044300e+04, 3.827420e+05, 6.797400e+04, 1.549300e+04,
       4.712300e+04, 1.011810e+05, 2.044280e+05, 8.446800e+04,
       1.693860e+05, 7.977200e+04, 2.522950e+05, 7.066800e+04,
       1.232100e+05, 1.236290e+05, 2.704710e+05, 1.430540e+05,
       3.270700e+04, 2.423400e+04, 2.504700e+04, 2.479700e+04,
       7.945000e+03, 2.601800e+04, 8.217000e+03, 3.109000e+04,
       6.112000e+03, 1.230400e+04, 7.981000e+03, 4.682000e+03,
       4.944000e+03, 4.306000e+03, 6.185000e+03, 4.860000e+03,
       8.775700e+04, 2.265800e+04, 5.830000e+03, 2.777000e+03,
       2.663000e+04, 1.020900e+04, 2.172500e+04, 1.394200e+04,
       1.682700e+04, 1.260600e+04, 6.724000e+03, 1.2712

In [17]:
U.shape

(408, 425)

In [18]:
V.shape

(403, 403)

In [19]:
g = U.values[-1,:402]

In [20]:
g.shape

(402,)

In [21]:
q = U.values[:402,-1]

In [22]:
q.shape

(402,)

In [23]:
q

array([3.792200e+04, 5.725900e+04, 1.858200e+04, 2.973100e+04,
       1.986800e+04, 2.487500e+04, 3.810600e+04, 8.744500e+04,
       4.416500e+04, 3.323700e+04, 2.132500e+04, 9.239000e+03,
       2.971800e+04, 2.126640e+05, 2.780100e+04, 1.168800e+04,
       1.562700e+04, 1.447700e+04, 1.488300e+04, 2.857900e+04,
       8.969100e+04, 4.557620e+05, 8.021400e+04, 8.096700e+04,
       4.712300e+04, 1.011810e+05, 2.044280e+05, 8.446800e+04,
       1.693860e+05, 7.977200e+04, 2.522950e+05, 7.066800e+04,
       1.232100e+05, 1.236290e+05, 2.704710e+05, 1.430540e+05,
       3.595300e+04, 2.398600e+04, 2.193900e+04, 2.521600e+04,
       8.352000e+03, 2.622700e+04, 8.070000e+03, 3.065500e+04,
       6.104000e+03, 1.248000e+04, 8.067000e+03, 4.724000e+03,
       4.943000e+03, 4.070000e+03, 6.179000e+03, 5.103000e+03,
       1.019730e+05, 9.247000e+03, 8.816000e+03, 2.554600e+04,
       1.547200e+04, 1.993000e+04, 1.056100e+04, 1.649300e+04,
       1.232400e+04, 6.712000e+03, 1.304200e+04, 1.0943

## Closed model

In [24]:
compensation = U.values[403,:402]
wage_coefficient = compensation / gd

In [25]:
wage_coefficient.max()

np.float64(1.5861294896030245)

In [26]:
wage_coefficient.mean()

np.float64(0.2731996257174114)

In [27]:
wage_coefficient[wage_coefficient>1.0]

array([1.58612949])

In [28]:
AC = np.zeros((403,403))

In [29]:
AC[:402,:402] = A

In [30]:
AC[402,:402] = wage_coefficient

In [31]:
PCE = U.values[:402,403]
PCE.shape

(402,)

In [32]:
PCE

array([ 0.000000e+00,  2.483000e+03,  1.988100e+04,  2.449900e+04,
        1.318900e+04,  3.958000e+03,  1.650000e+02,  9.700000e+01,
        5.227000e+03,  6.023000e+03,  0.000000e+00,  6.448000e+03,
        1.240000e+02,  0.000000e+00,  1.210000e+02,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  5.200000e+01,  0.000000e+00,
        0.000000e+00,  1.776610e+05,  4.815200e+04,  3.960300e+04,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  3.143000e+03,
        2.530000e+03,  5.566000e+03,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  5.300000e+01,  2.600000e+01,  1.880000e+02,
        3.169000e+03,  4.100000e+01,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  6.740000e+02,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  5.300000e+01,  0.000000e

In [33]:
c = PCE/PCE.sum()

In [34]:
c

array([ 0.00000000e+00,  1.86823306e-04,  1.49586555e-03,  1.84332830e-03,
        9.92353035e-04,  2.97803724e-04,  1.24147586e-05,  7.29837322e-06,
        3.93284503e-04,  4.53176308e-04,  0.00000000e+00,  4.85153717e-04,
        9.32987917e-06,  0.00000000e+00,  9.10415629e-06,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  3.91252998e-06,  0.00000000e+00,
        0.00000000e+00,  1.33673844e-02,  3.62300276e-03,  2.97976778e-03,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.36482341e-04,
        1.90359631e-04,  4.18791189e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.98777094e-06,  1.95626499e-06,  1.41453007e-05,
        2.38438606e-04,  3.08487940e-06,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [35]:
AC[:402,402] = c

In [36]:
AC[:,402]

array([ 0.00000000e+00,  1.86823306e-04,  1.49586555e-03,  1.84332830e-03,
        9.92353035e-04,  2.97803724e-04,  1.24147586e-05,  7.29837322e-06,
        3.93284503e-04,  4.53176308e-04,  0.00000000e+00,  4.85153717e-04,
        9.32987917e-06,  0.00000000e+00,  9.10415629e-06,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  3.91252998e-06,  0.00000000e+00,
        0.00000000e+00,  1.33673844e-02,  3.62300276e-03,  2.97976778e-03,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.36482341e-04,
        1.90359631e-04,  4.18791189e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.98777094e-06,  1.95626499e-06,  1.41453007e-05,
        2.38438606e-04,  3.08487940e-06,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [37]:
c.max()

np.float64(0.11686260541540798)

In [38]:
LC = np.linalg.inv(np.eye(403)-AC)

In [39]:
MC = LC.sum(axis=0)

In [40]:
MC

array([ 3.54798748,  5.56408201,  4.75471903,  4.14286852,  5.2303695 ,
        5.50251165,  5.19524261,  4.3302695 ,  6.16014541,  2.95434527,
        6.48343261,  2.7340949 ,  6.00252376,  3.44207284,  4.95162044,
        4.2214075 ,  5.12662012,  4.69233879,  5.15992044,  4.96011139,
        5.19587   ,  3.52172009,  4.26131608,  4.36591577,  5.8264571 ,
        5.71628137,  5.52525241,  5.53078034,  5.88980721,  5.62426079,
        5.34480373,  5.67891438,  5.70377755,  5.07266635,  5.86411881,
        5.57852255,  6.29728497,  5.91402118,  6.19812674,  6.40931255,
        5.86548492,  5.31442313,  4.25502396,  5.58876985,  5.45077883,
        5.63795468,  4.5532798 ,  3.75549199,  6.06022366,  4.51642182,
        4.99526898,  4.68251641,  5.87143287,  6.27873958,  6.35719977,
        6.13156474,  6.39738926,  5.12871366,  6.38617512,  5.5154742 ,
        6.02258812,  6.27923216,  5.75755199,  6.28854773,  6.35534199,
        5.93880724,  6.39087912,  6.30752198,  6.03675528,  6.22

In [41]:
A[0:4,0:4]

array([[2.18232928e-01, 8.69411027e-03, 2.87011434e-03, 7.35513928e-04],
       [4.40318590e-04, 1.34680637e-01, 1.56514769e-03, 1.54909943e-03],
       [1.58841487e-04, 6.33114093e-04, 3.59788449e-02, 6.25586303e-04],
       [1.61177212e-04, 6.42424417e-04, 5.72918364e-04, 2.55353330e-02]])

In [42]:
AC[0:4, 0:4]

array([[2.18232928e-01, 8.69411027e-03, 2.87011434e-03, 7.35513928e-04],
       [4.40318590e-04, 1.34680637e-01, 1.56514769e-03, 1.54909943e-03],
       [1.58841487e-04, 6.33114093e-04, 3.59788449e-02, 6.25586303e-04],
       [1.61177212e-04, 6.42424417e-04, 5.72918364e-04, 2.55353330e-02]])

## Multipliers

In [43]:
SO = L.sum(axis=0)

In [44]:
np.median(SO)

np.float64(2.047895936665034)

In [45]:
TIIO = LC.sum(axis=0)[:-1]

In [46]:
np.median(TIIO)

np.float64(5.696236941861624)

In [47]:
U.iloc[:402,[0,1]]

,Oilseed farming,Grain farming
0,8332.0,455.0
1,0.0,7694.0
2,0.0,0.0
3,0.0,0.0
4,0.0,0.0
...,...,...
397,0.0,0.0
398,0.0,0.0
399,0.0,0.0
400,111.0,371.0


In [48]:
SO[0:4]

array([2.05558814, 2.69238156, 2.08768823, 1.71722196])

In [49]:
TIIO[0:4]

array([3.54798748, 5.56408201, 4.75471903, 4.14286852])

In [50]:
A.shape, g.shape

((402, 402), (402,))

In [51]:
Z = A @ np.diag(g)

In [52]:
Z[0:4, 0:4]

array([[8.33998957e+03, 5.03232491e+02, 5.39753702e+01, 2.20345263e+01],
       [1.68272152e+01, 7.79558465e+03, 2.94341675e+01, 4.64079208e+01],
       [6.07028627e+00, 3.66459099e+01, 6.76618157e+02, 1.87413145e+01],
       [6.15954835e+00, 3.71848101e+01, 1.07743027e+01, 7.64987507e+02]])

In [53]:
Z.shape

(402, 402)

In [54]:
# nonzero cells
nzc = (Z==0).sum(axis=1)

In [55]:
nzc[0:4]

array([195, 189, 196, 190])

In [56]:
U.head()

,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",Poultry and egg production,"Animal production, except cattle and poultry and eggs",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,1597.0,175.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0


In [57]:
sectors = U.columns[0:402]

In [58]:
sectors

Index(['Oilseed farming', 'Grain farming', 'Vegetable and melon farming',
       'Fruit and tree nut farming',
       'Greenhouse, nursery, and floriculture production',
       'Other crop farming', 'Dairy cattle and milk production',
       'Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming',
       'Poultry and egg production',
       'Animal production, except cattle and poultry and eggs',
       ...
       'Federal general government (nondefense)', 'Postal service',
       'Federal electric utilities', 'Other federal government enterprises',
       'State and local government (educational services)',
       'State and local government (hospitals and health services)',
       'State and local government (other services)',
       'State and local government passenger transit',
       'State and local government electric utilities',
       'Other state and local government enterprises'],
      dtype='object', length=402)

In [59]:
U.sort_values(by='Grain farming', ascending=False).head(25)

,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",Poultry and egg production,"Animal production, except cattle and poultry and eggs",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
407,38216.0,57882.0,18806.0,29958.0,20064.0,26575.0,38538.0,88052.0,44568.0,33443.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
402,20547.0,48075.0,10655.0,11723.0,9659.0,17494.0,28922.0,60750.0,38756.0,10294.0,...,379143.0,19195.0,109261.0,10161.0,1737213.0,44204.0,44768.0,304902.0,19612103.0,34468130.0
405,15495.0,14896.0,5165.0,12227.0,4492.0,4298.0,6583.0,24181.0,2239.0,19371.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
406,17670.0,9807.0,8151.0,18235.0,10405.0,9081.0,9616.0,27302.0,5812.0,23149.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1326.0,8007.0,2320.0,3658.0,1218.0,3169.0,1087.0,913.0,720.0,502.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.0,29718.0
1,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,1597.0,175.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
275,3444.0,6843.0,1035.0,889.0,1182.0,1530.0,4319.0,5465.0,6599.0,1146.0,...,0.0,26.0,9.0,0.0,0.0,72.0,18.0,0.0,197614.0,384877.0
250,1006.0,4234.0,1184.0,1132.0,407.0,1675.0,796.0,352.0,136.0,162.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2090.0,15045.0
249,482.0,3608.0,782.0,525.0,500.0,676.0,406.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3876.0,17142.0
403,1062.0,3149.0,2497.0,5182.0,5551.0,4823.0,2179.0,1231.0,2521.0,2793.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [60]:
U.index

RangeIndex(start=0, stop=408, step=1)

In [61]:
sectors[[12,1, 275, 250, 249, 234, 321, 23, 290]]

Index(['Support activities for agriculture and forestry', 'Grain farming',
       'Petroleum and petroleum products', 'Fertilizer manufacturing',
       'Biological product (except diagnostic) manufacturing',
       'Support activities for printing', 'Tenant-occupied housing',
       'Water, sewage and other systems', 'Water transportation'],
      dtype='object')

In [62]:
U402 = U.values[0:402, 1]

In [63]:
U402.shape

(402,)

In [64]:
sectors = sectors.values

In [65]:
U402.searchsorted?

Docstring:
a.searchsorted(v, side='left', sorter=None)

Find indices where elements of v should be inserted in a to maintain order.

For full documentation, see `numpy.searchsorted`

See Also
--------
numpy.searchsorted : equivalent function
Type:      builtin_function_or_method

a = np.array([40, 10, 20, 30])
sorter = np.argsort(a)
sorter
result = np.searchsorted(a, 25, sorter=sorter)
result
a[sorter[result]]

In [66]:
sidx = np.argsort(U402)

In [67]:
U402[sidx]

array([0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 

In [68]:
sidx[::-1]

array([ 12,   1, 275, 250, 249, 234, 321,  23, 290, 288, 323,  81,   5,
       137, 274,   0, 400, 283,  18,  26,  22, 264, 316, 289, 270,   7,
        21, 312, 330,  17, 241,   9, 269, 267, 342, 151, 155, 271, 322,
       339, 258, 328, 375, 326, 292, 317,  64, 349, 295, 306, 305, 329,
       379, 314, 273, 287, 280, 265,  65, 263,  53, 378, 276, 256, 325,
       300, 311, 186, 279,  72, 388,  80, 272, 134, 150, 367, 153, 307,
       376, 377, 313,  39, 366, 285, 380, 297, 257, 346, 392, 107, 373,
       232, 268, 345, 351, 216, 103, 111, 230, 229, 228, 227, 281, 278,
       348, 335, 154, 121, 122, 138, 123, 124, 136, 135, 133, 139,  86,
        87,  88, 157, 359, 360, 361, 131, 363,  76, 156,  77,  78, 129,
       130, 125, 132, 362, 110, 112, 166, 167, 168, 169, 165, 170, 127,
       163, 162, 171, 172, 173, 158, 159, 161, 160, 164, 126, 128, 113,
       152, 149, 114,  85, 115, 109, 117, 118, 119, 120, 105, 148, 106,
       147, 108, 116,  44,  45,  46,  47, 390, 399,   2,   3,  9

In [69]:
U402[sidx[::-1][:10]].sum() / U402.sum()

np.float64(0.8022259205325567)

In [70]:
U402[sidx[::-1][:20]].sum() / U402.sum()

np.float64(0.8949448720615769)

In [71]:
U402[sidx[::-1][:30]].sum() / U402.sum()

np.float64(0.944247971707926)

In [72]:
def disaggregate_aij(aij, zeta_i, alpha):
    aij1 = aij / ((1-alpha) + alpha * zeta_i)
    aij2 = aij1 * zeta_i

    return (aij, aij1, aij2)

In [73]:
aij, aij1, aij2 = disaggregate_aij(0.25, 1.24, .4)
aij, aij1, aij2

(0.25, 0.22810218978102187, 0.2828467153284671)

In [74]:
aij1 *.6 + .4 * aij2

0.24999999999999994

In [75]:
aij, aij1, aij2 = disaggregate_aij(0.25, 0.75, .4)

In [76]:
aij1 *.6 + .4 * aij2

0.25

In [77]:
aij1, aij2

(0.2777777777777778, 0.20833333333333334)

In [78]:
import numpy as np


def disaggregate_sector(A, j, alpha, zeta, copy=True):
    """
    Disaggregate sector j in an input-output coefficient matrix A into
    two subsectors:
        j1 = annual grain
        j2 = perennial grain

    Parameters
    ----------
    A : array_like, shape (n, n)
        Technical coefficients matrix.
    j : int
        Index of the sector/column to split.
    alpha : float
        Share of the original sector allocated to the second subsector
        (e.g. perennial grain). Must satisfy 0 <= alpha <= 1.
    zeta : array_like, shape (n,)
        Row-specific relative intensity coefficients, where
            zeta[i] = a[i, j, 2] / a[i, j, 1]
    copy : bool, default True
        If True, work on a copy of A.

    Returns
    -------
    A_new : ndarray, shape (n + 1, n + 1)
        Expanded coefficient matrix with sector j replaced by two sectors.
        The ordering is:
            [0, ..., j-1, j1, j2, j+1, ..., n-1]
    info : dict
        Dictionary containing useful intermediate results:
            - 'a1': first split column
            - 'a2': second split column
            - 'original_column': original A[:, j]
            - 'alpha': alpha
            - 'zeta': zeta

    Notes
    -----
    This function only splits the *column* j, i.e. the input structure
    of the sector. If you also want to split the *row* j (sales/output
    distribution), that requires an additional assumption/system.

    The original row/column j is replaced by two sectors, but the row
    split here is done by simple duplication with proportional allocation:
        row_j1 = (1 - alpha) * row_j
        row_j2 = alpha * row_j
    except for the intersection block, which is filled consistently from
    the split columns.

    In many applications, you may want a more defensible row-splitting rule.
    """
    A = np.array(A, dtype=float, copy=copy)
    n, m = A.shape
    if n != m:
        raise ValueError("A must be a square matrix.")

    if not (0 <= j < n):
        raise IndexError("j is out of bounds.")

    if not (0 <= alpha <= 1):
        raise ValueError("alpha must be between 0 and 1.")

    zeta = np.asarray(zeta, dtype=float)
    if zeta.shape != (n,):
        raise ValueError(f"zeta must have shape ({n},), got {zeta.shape}.")

    if np.any(zeta < 0):
        raise ValueError("All zeta values must be nonnegative.")

    # Original column to split
    a = A[:, j]

    # Denominator for exact identity preservation
    denom = (1 - alpha) + alpha * zeta
    if np.any(denom == 0):
        raise ValueError("Encountered zero denominator in split formula.")

    # Split columns
    a1 = a / denom
    a2 = zeta * a1

    # Build expanded matrix
    A_new = np.zeros((n + 1, n + 1), dtype=float)

    # Indices in new matrix
    # old indices < j stay the same
    # old index j becomes j and j+1
    # old indices > j shift by +1
    def new_index(old_idx):
        if old_idx < j:
            return old_idx
        elif old_idx > j:
            return old_idx + 1
        else:
            raise ValueError("Original split index maps to two positions.")

    # Copy all unaffected cells
    for r in range(n):
        for c in range(n):
            if r == j or c == j:
                continue
            rr = new_index(r)
            cc = new_index(c)
            A_new[rr, cc] = A[r, c]

    # Split the target column j into j and j+1
    for r in range(n):
        rr = r if r < j else r + 1
        if r == j:
            # handled below in 2x2 block
            continue
        A_new[rr, j] = a1[r]
        A_new[rr, j + 1] = a2[r]

    # Split the target row j proportionally
    row = A[j, :]
    for c in range(n):
        if c == j:
            continue
        cc = c if c < j else c + 1
        A_new[j, cc] = (1 - alpha) * row[c]
        A_new[j + 1, cc] = alpha * row[c]

    # Fill the 2x2 intersection block consistently
    # Original self-coefficient A[j, j] is split using same rule
    a_jj = A[j, j]
    denom_j = (1 - alpha) + alpha * zeta[j]
    a1_j = a_jj / denom_j
    a2_j = zeta[j] * a1_j

    # Allocate self/input relations proportionally by output shares
    A_new[j, j] = (1 - alpha) * a1_j
    A_new[j + 1, j] = alpha * a1_j
    A_new[j, j + 1] = (1 - alpha) * a2_j
    A_new[j + 1, j + 1] = alpha * a2_j

    info = {
        "a1": a1,
        "a2": a2,
        "original_column": a,
        "alpha": alpha,
        "zeta": zeta,
    }

    return A_new, info

In [79]:
A = np.array([
    [0.10, 0.20, 0.15],
    [0.05, 0.10, 0.20],
    [0.08, 0.12, 0.10],
])

# Split sector 1 (grain farming)
alpha = 0.25
zeta = np.array([1.2, 0.8, 1.5])

A_new, info = disaggregate_sector(A, j=1, alpha=alpha, zeta=zeta)

print("Original A:")
print(A)
print("\nExpanded A:")
print(A_new)
print("\nAnnual column:")
print(info["a1"])
print("\nPerennial column:")
print(info["a2"])

Original A:
[[0.1  0.2  0.15]
 [0.05 0.1  0.2 ]
 [0.08 0.12 0.1 ]]

Expanded A:
[[0.1        0.19047619 0.22857143 0.15      ]
 [0.0375     0.07894737 0.06315789 0.15      ]
 [0.0125     0.02631579 0.02105263 0.05      ]
 [0.08       0.10666667 0.16       0.1       ]]

Annual column:
[0.19047619 0.10526316 0.10666667]

Perennial column:
[0.22857143 0.08421053 0.16      ]


In [80]:
A = np.array([
    [0.10, 0.20, 0.15],
    [0.05, 0.10, 0.20],
    [0.08, 0.12, 0.10],
])

# Split sector 1 (grain farming)
alpha = 0.25
zeta = np.array([1.2, 1, 1.])

A_new, info = disaggregate_sector(A, j=1, alpha=alpha, zeta=zeta)

print("Original A:")
print(A)
print("\nExpanded A:")
print(A_new)
print("\nAnnual column:")
print(info["a1"])
print("\nPerennial column:")
print(info["a2"])

Original A:
[[0.1  0.2  0.15]
 [0.05 0.1  0.2 ]
 [0.08 0.12 0.1 ]]

Expanded A:
[[0.1        0.19047619 0.22857143 0.15      ]
 [0.0375     0.075      0.075      0.15      ]
 [0.0125     0.025      0.025      0.05      ]
 [0.08       0.12       0.12       0.1       ]]

Annual column:
[0.19047619 0.1        0.12      ]

Perennial column:
[0.22857143 0.1        0.12      ]


In [81]:
A = np.array([
    [0.10, 0.20, 0.15],
    [0.05, 0.10, 0.20],
    [0.08, 0.12, 0.10],
])

# Split sector 1 (grain farming)
alpha = 0.10
zeta = np.array([1.2, 1, 1.])

A_new, info = disaggregate_sector(A, j=1, alpha=alpha, zeta=zeta)

print("Original A:")
print(A)
print("\nExpanded A:")
print(A_new)
print("\nAnnual column:")
print(info["a1"])
print("\nPerennial column:")
print(info["a2"])

Original A:
[[0.1  0.2  0.15]
 [0.05 0.1  0.2 ]
 [0.08 0.12 0.1 ]]

Expanded A:
[[0.1        0.19607843 0.23529412 0.15      ]
 [0.045      0.09       0.09       0.18      ]
 [0.005      0.01       0.01       0.02      ]
 [0.08       0.12       0.12       0.1       ]]

Annual column:
[0.19607843 0.1        0.12      ]

Perennial column:
[0.23529412 0.1        0.12      ]
