In [1]:
import numpy as np
import pandas as pd

use = pd.read_excel(
    "../data/raw/io/IOUse_After_Redefinitions_PRO_Detail.xlsx",
    sheet_name="2017",
    skiprows=[0,1,2,3]
)

make = pd.read_excel(
    "../data/raw/io/IOMake_After_Redefinitions_PRO_Detail.xlsx",
    sheet_name="2017",
    skiprows=[0,1,2,3]
)

In [2]:
make.head()

,Industry / Commodity,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Other federal government enterprises,State and local government (educational services),State and local government (hospitals and health services),State and local government (other services),Other state and local government enterprises,Scrap,Used and secondhand goods,Noncomparable imports,Rest of the world adjustment,Total Industry Output
0,Code,Industry Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,S00102,GSLGE,GSLGH,GSLGO,S00203,S00401,S00402,S00300,S00900,T008
1,1111A0,Oilseed farming,37922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38216
2,1111B0,Grain farming,NaN,57259,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57882
3,111200,Vegetable and melon farming,NaN,NaN,18582.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18806
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,29731.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29958


In [3]:
new_cols = make.columns.astype(str) + "_" + make.iloc[0].astype(str)
make.cols=new_cols
make= make.iloc[1:].reset_index(drop=True)

/tmp/ipykernel_467713/3369136407.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  make.cols=new_cols


In [4]:
make.head()

,Industry / Commodity,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Other federal government enterprises,State and local government (educational services),State and local government (hospitals and health services),State and local government (other services),Other state and local government enterprises,Scrap,Used and secondhand goods,Noncomparable imports,Rest of the world adjustment,Total Industry Output
0,1111A0,Oilseed farming,37922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38216
1,1111B0,Grain farming,NaN,57259,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57882
2,111200,Vegetable and melon farming,NaN,NaN,18582.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18806
3,111300,Fruit and tree nut farming,NaN,NaN,NaN,29731.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29958
4,111400,"Greenhouse, nursery, and floriculture production",NaN,NaN,NaN,NaN,19840.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20064


In [5]:
V =make.iloc[:,2:].fillna(0).values.astype(int)

/tmp/ipykernel_467713/1866238292.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  V =make.iloc[:,2:].fillna(0).values.astype(int)


In [6]:
V.shape

(403, 403)

In [7]:
V

array([[   37922,        0,        0, ...,        0,        0,    38216],
       [       0,    57259,        0, ...,        0,        0,    57882],
       [       0,        0,    18582, ...,        0,        0,    18806],
       ...,
       [       0,        0,        0, ...,        0,        0,    63412],
       [       0,        0,        0, ...,        0,        0,   273909],
       [   37922,    57259,    18582, ...,        0,     3468, 34468130]],
      shape=(403, 403))

In [8]:
q = V[-1,:-1]


In [9]:
q

array([  37922,   57259,   18582,   29731,   19868,   24875,   38106,
         87445,   44165,   33237,   21325,    9239,   29718,  212664,
         27801,   11688,   15627,   14477,   14883,   28579,   89691,
        455762,   80214,   80967,   47123,  101181,  204428,   84468,
        169386,   79772,  252295,   70668,  123210,  123629,  270471,
        143054,   35953,   23986,   21939,   25216,    8352,   26227,
          8070,   30655,    6104,   12480,    8067,    4724,    4943,
          4070,    6179,    5103,  101973,    9247,    8816,   25546,
         15472,   19930,   10561,   16493,   12324,    6712,   13042,
         10943,    8756,   43306,   41400,    6971,    8055,   17580,
          8728,    5645,   37044,   29110,   26122,    4470,   24115,
          5983,    5949,   13063,   13901,   24691,    7392,   32074,
         16946,   14325,   24425,    4553,    1179,   18358,    4384,
         32793,    5836,    6385,   10307,    7601,    8384,   12065,
          3031,    4

In [10]:
qden = q + (q==0)*1

In [11]:
D = V[:-1, :-1] @ np.diag( 1 / qden)

In [12]:
D.sum(axis=0)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.00003009,
       1.        , 1.        , 1.00003365, 0.9999953 , 1.        ,
       1.        , 1.        , 1.        , 1.00006719, 0.99996501,
       1.        , 1.        , 1.        , 0.99998765, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.99995442, 1.        ,
       0.99976054, 1.00003813, 1.        , 0.99996738, 0.99983617,
       1.        , 1.        , 1.        , 1.        , 1.0002457 ,
       1.        , 1.        , 1.        , 1.00010814, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99991886, 0.99985101, 0.99984665, 0.99990862, 0.99977159,
       0.99997691, 0.99992754, 0.99985655, 0.99987585, 1.        ,
       0.99988543, 0.99982285, 1.        , 0.9999313 , 1.     

In [13]:
A = D @ B

NameError: name 'B' is not defined

In [14]:
A.shape

NameError: name 'A' is not defined

In [16]:
L = np.linalg.inv(np.eye(402) - A)

NameError: name 'A' is not defined

In [17]:
mults = L.sum(axis=0)

NameError: name 'L' is not defined

In [17]:
mults

NameError: name 'mults' is not defined

In [18]:
mults.max()

NameError: name 'mults' is not defined

In [19]:
mults.min()

NameError: name 'mults' is not defined

In [20]:
mults[0:4]

NameError: name 'mults' is not defined

In [262]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,Code,Commodity Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,F07C00,F07E00,F07N00,F07S00,F10C00,F10E00,F10N00,F10S00,T004,T007
1,1111A0,Oilseed farming,8332,455,40.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
2,1111B0,Grain farming,NaN,7694,NaN,NaN,NaN,446.0,1697.0,4253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
3,111200,Vegetable and melon farming,NaN,NaN,666.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,748.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731


In [269]:
E = use.iloc[1:,405:].fillna(0)

In [270]:
E

,Personal consumption expenditures,Nonresidential private fixed investment in equipment,Nonresidential private fixed investment in intellectual property products,Residential private fixed investment,Nonresidential private fixed investment in structures,Change in private inventories,Exports of goods and services,Imports of goods and services,Federal Government defense: Consumption expenditures,Federal national defense: Gross investment in equipment,...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
1,0,0,0,0,0,-1330,12088,-963,0,0,...,0,0,0,0,0,0,0,0,9796,37922
2,2483,0,0,0,0,-2056,8886,-1647,0,0,...,0,0,0,0,0,0,0,0,7666,57259
3,19881,0,0,0,0,-673,2426,-8403,0,0,...,0,0,0,0,0,0,0,0,13231,18582
4,24499,0,0,0,0,-758,5750,-19324,0,0,...,0,0,0,0,0,0,0,0,10167,29731
5,13189,0,0,0,0,84,710,-2688,0,0,...,0,0,0,0,0,0,0,0,11295,19868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [274]:
E.values[-6:]

array([[13290625, 1159953, 906246, 773891, 594900, 32674, 2082977,
        -2626305, 599358, 77264, 63714, 7956, 379143, 19195, 109261,
        10161, 1737213, 44204, 44768, 304902, 19612103, 34468130],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=object)

In [68]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,Code,Commodity Description,1111A0,1111B0,111200.0,111300.0,111400.0,111900.0,112120.0,1121A0,...,F07C00,F07E00,F07N00,F07S00,F10C00,F10E00,F10N00,F10S00,T004,T007
1,1111A0,Oilseed farming,8332,455,40.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
2,1111B0,Grain farming,NaN,7694,NaN,NaN,NaN,446.0,1697.0,4253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
3,111200,Vegetable and melon farming,NaN,NaN,666.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
4,111300,Fruit and tree nut farming,NaN,NaN,NaN,748.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731


In [69]:
new_cols = use.columns.astype(str) + "_" + use.iloc[0].astype(str)

In [70]:
use.cols=new_cols
use= use.iloc[1:].reset_index(drop=True)

/tmp/ipykernel_11359/726143188.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  use.cols=new_cols


In [86]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0


In [87]:
use.shape

(408, 427)

In [72]:
use.iloc[:,2:] = (use.iloc[:,2:].apply(pd.to_numeric, errors='coerce').fillna(0.0))

In [73]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0


In [74]:
use.tail(10)

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
398,S00401,Scrap,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-19722.0,10763.0
399,S00402,Used and secondhand goods,0.0,0.0,0.0,0.0,-18.0,0.0,0.0,0.0,...,0.0,-4.0,0.0,-2683.0,0.0,-14497.0,0.0,3909.0,-27562.0,0.0
400,S00300,Noncomparable imports,111.0,371.0,0.0,0.0,0.0,0.0,181.0,172.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-142489.0,0.0
401,S00900,Rest of the world adjustment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3468.0,3468.0
402,T005,Total Intermediate,20547.0,48075.0,10655.0,11723.0,9659.0,17494.0,28922.0,60750.0,...,379143.0,19195.0,109261.0,10161.0,1737213.0,44204.0,44768.0,304902.0,19612103.0,34468130.0
403,V00100,Compensation of employees,1062.0,3149.0,2497.0,5182.0,5551.0,4823.0,2179.0,1231.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
404,V00200,"Taxes on production and imports, less subsidies",1112.0,-8237.0,489.0,826.0,362.0,-41.0,853.0,1890.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,V00300,Gross operating surplus,15495.0,14896.0,5165.0,12227.0,4492.0,4298.0,6583.0,24181.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
406,T006,Total Value Added,17670.0,9807.0,8151.0,18235.0,10405.0,9081.0,9616.0,27302.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
407,T008,Total Industry Output,38216.0,57882.0,18806.0,29958.0,20064.0,26575.0,38538.0,88052.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [78]:
list(use.columns.values)

['Commodities/Industries',
 'Unnamed: 1',
 'Oilseed farming',
 'Grain farming',
 'Vegetable and melon farming',
 'Fruit and tree nut farming',
 'Greenhouse, nursery, and floriculture production',
 'Other crop farming',
 'Dairy cattle and milk production',
 'Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming',
 'Poultry and egg production',
 'Animal production, except cattle and poultry and eggs',
 'Forestry and logging',
 'Fishing, hunting and trapping',
 'Support activities for agriculture and forestry',
 'Oil and gas extraction',
 'Coal mining',
 'Copper, nickel, lead, and zinc mining',
 'Iron, gold, silver, and other metal ore mining',
 'Stone mining and quarrying',
 'Other nonmetallic mineral mining and quarrying',
 'Drilling oil and gas wells',
 'Other support activities for mining',
 'Electric power generation, transmission, and distribution',
 'Natural gas distribution',
 'Water, sewage and other systems',
 'Health care structures',
 'Educ

In [84]:
use.iloc[0:2,403] # 403 is last industry

0    0.0
1    0.0
Name: Other state and local government enterprises, dtype: object

In [88]:
use.shape

(408, 427)

In [146]:
g = use.iloc[407,2:404] # total industry output
g

Oilseed farming                                                38216.0
Grain farming                                                  57882.0
Vegetable and melon farming                                    18806.0
Fruit and tree nut farming                                     29958.0
Greenhouse, nursery, and floriculture production               20064.0
                                                                ...   
State and local government (hospitals and health services)    309771.0
State and local government (other services)                   866778.0
State and local government passenger transit                   16928.0
State and local government electric utilities                  63412.0
Other state and local government enterprises                  273909.0
Name: 407, Length: 402, dtype: object

In [147]:
g = g.astype(int)

In [148]:
g

Oilseed farming                                                38216
Grain farming                                                  57882
Vegetable and melon farming                                    18806
Fruit and tree nut farming                                     29958
Greenhouse, nursery, and floriculture production               20064
                                                               ...  
State and local government (hospitals and health services)    309771
State and local government (other services)                   866778
State and local government passenger transit                   16928
State and local government electric utilities                  63412
Other state and local government enterprises                  273909
Name: 407, Length: 402, dtype: int64

In [195]:
q = use.iloc[0:402, -1].astype(int).values # total commodity output

In [196]:
q[-10:]

array([ 69564,   1233, 832472,  68698, 836043, 107059,  10763,      0,
            0,   3468])

In [197]:
g.sum()

np.int64(34468137)

In [198]:
q.sum()

np.int64(34468138)

In [199]:
U = use.iloc[0:402, 2:404].astype(int)

In [200]:
use.head()

,Commodities/Industries,Unnamed: 1,Oilseed farming,Grain farming,Vegetable and melon farming,Fruit and tree nut farming,"Greenhouse, nursery, and floriculture production",Other crop farming,Dairy cattle and milk production,"Beef cattle ranching and farming, including feedlots and dual-purpose ranching and farming",...,Federal Government nondefense: Consumption expenditures,Federal nondefense: Gross investment in equipment,Federal nondefense: Gross investment in intellectual property products,Federal nondefense: Gross investment in structures,State and local government consumption expenditures,State and local: Gross investment in equipment,State and local: Gross investment in intellectual property products,State and local: Gross investment in structures,Total Final Uses (GDP),Total Commodity Output
0,1111A0,Oilseed farming,8332.0,455.0,40.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9796.0,37922.0
1,1111B0,Grain farming,0.0,7694.0,0.0,0.0,0.0,446.0,1697.0,4253.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7666.0,57259.0
2,111200,Vegetable and melon farming,0.0,0.0,666.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13231.0,18582.0
3,111300,Fruit and tree nut farming,0.0,0.0,0.0,748.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10167.0,29731.0
4,111400,"Greenhouse, nursery, and floriculture production",0.0,0.0,0.0,0.0,2640.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11295.0,19868.0


In [201]:
U.shape

(402, 402)

In [202]:
g.shape

(402,)

In [203]:
gden = g + (g==0)
gden = gden.values


In [204]:
gden.shape

(402,)

In [205]:
U.shape

(402, 402)

In [206]:
U.sum(axis=0)

Oilseed farming                                                20547
Grain farming                                                  48070
Vegetable and melon farming                                    10654
Fruit and tree nut farming                                     11717
Greenhouse, nursery, and floriculture production                9659
                                                               ...  
State and local government (hospitals and health services)    155507
State and local government (other services)                   333166
State and local government passenger transit                   26997
State and local government electric utilities                  33922
Other state and local government enterprises                  148806
Length: 402, dtype: int64

In [207]:
B = U @ np.diag(1/gden)

In [208]:
B.sum(axis=0)

0      0.537654
1      0.830483
2      0.566521
3      0.391114
4      0.481409
         ...   
397    0.502006
398    0.384373
399    1.594813
400    0.534946
401    0.543268
Length: 402, dtype: float64

In [209]:
Bsum = B.sum(axis=0)

In [210]:
Bsum.sort_values()

390    0.000000
278    0.000000
311    0.022953
321    0.055989
110    0.109267
         ...   
54     0.874443
319    0.899600
193    0.917673
395    1.354485
399    1.594813
Length: 402, dtype: float64

In [211]:
U.shape

(402, 402)

In [212]:
U = U.values

In [213]:
U[:,395]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         15,    0,    0,    0,    0,    0,    0,    0,    0,    0,  138,
        136,  112,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    3,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    4,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    1,    0,    0,   46,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [214]:
use.iloc[0,[395, 399]]


Postal service                                                0.0
State and local government (hospitals and health services)    0.0
Name: 0, dtype: object

In [219]:
g.iloc[[395, 399]] # these have negative value added

Other federal government enterprises             6209
State and local government passenger transit    16928
Name: 407, dtype: int64

In [48]:
use.iloc[6][use.iloc[6]=='S00203']

Series([], Name: 6, dtype: object)

In [46]:
17670+20547

38217

In [42]:
flows

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 417,Unnamed: 418,Unnamed: 419,Unnamed: 420,Unnamed: 421,Unnamed: 422,Unnamed: 423,Unnamed: 424,Unnamed: 425,Unnamed: 426
5,8332,455,40,NaN,NaN,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,37922
6,NaN,7694,NaN,NaN,NaN,446,1697,4253,1597,175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7666,57259
7,NaN,NaN,666,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13231,18582
8,NaN,NaN,NaN,748,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10167,29731
9,NaN,NaN,NaN,NaN,2640,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11295,19868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,1062,3149,2497,5182,5551,4823,2179,1231,2521,2793,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,1112,-8237,489,826,362,-41,853,1890,1051,985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,15495,14896,5165,12227,4492,4298,6583,24181,2239,19371,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,17670,9807,8151,18235,10405,9081,9616,27302,5812,23149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
